module.exports = [
  {
    name: "Acura RDX",
    make: "Acura",
    model: "RDX",
    exterior: "ApxBlue Pearl",
    interior: "Ebony",
    year: 2022,
    drivetrain: "AWD",
    engine: "272-hp turbocharged 2.0-liter 4-cylinder",
    img: "https://i.imgur.com/M014xDL.png",
    price: 45995,
  },
  {
    name: "Prestige",
    make: "Audi",
    model: "S3",
    exterior: "Yellow",
    interior: "Black",
    year: 2017,
    drivetrain: "AWD",
    engine: "Inline 4-cylinder",
    img: "https://i.imgur.com/9HS7qXk.png",
    price: 22990,
  },
  {
    name: "Titanium",
    make: "Ford",
    model: "Escape",
    exterior: "Orange",
    interior: "Black",
    year: 2021,
    drivetrain: "AWD",
    engine: "2.5L iVCT Atkinson Cycle I-4 Hybrid",
    img: "https://i.imgur.com/l0hcG1Y.png",
    price: 36055,
  },
  {
    name: "Kia Sorento",
    make: "Kia",
    model: "Sorento",
    exterior: "Sparkling Silver",
    interior: "Sabre Black",
    year: 2020,
    drivetrain: "FWD",
    engine: "Regular Unleaded I-4",
    img: "https://i.imgur.com/cpxzDeN.png",
    price: 26990,
  },
  {
    name: "Lexus IS",
    make: "Lexus",
    model: "IS 350 F Sport",
    exterior: "Caviar",
    interior: "Circuit Red",
    year: 2022,
    drivetrain: "AWD",
    engine: "311-Horsepower V6",
    img: "https://i.imgur.com/MEHLoGh.png",
    price: 46275,
  }
]